;This file was auto-generated by drush_make
core = 6.x

api = 2

projects[drupal][version] = "6.19"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "1.6"

projects[content_profile][subdir] = "contrib"
projects[content_profile][version] = "1.0"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.7"

projects[data][subdir] = "contrib_modified"
projects[data][version] = "1.0-alpha14"
; Allow for any core filter to be selected: http://drupal.org/node/948426
projects[data][patch][] = "http://drupal.org/files/issues/select_any_core_handler_0.patch"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[diff][subdir] = "contrib"
projects[diff][version] = "2.1"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "1.0-beta10"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.0-alpha3"

projects[filefield][subdir] = "contrib"
projects[filefield][version] = "3.7"

projects[install_profile_api][subdir] = "contrib"
projects[install_profile_api][version] = "2.1"

projects[jquery_ui][subdir] = "contrib_modified"
projects[jquery_ui][version] = "1.4"
; Allow jQuery UI module to find library in libraries dir: http://drupal.org/node/489140
projects[jquery_ui][patch][] = "http://drupal.org/files/issues/jquery_ui_489140_37.patch"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "1.0-beta3"

projects[location][subdir] = "contrib"
projects[location][version] = "3.1"

projects[schema][subdir] = "contrib"
projects[schema][version] = "1.7"

projects[vertical_tabs][subdir] = "contrib"
projects[vertical_tabs][version] = "1.0-rc1"

projects[vt_default][subdir] = "contrib_modified"
projects[vt_default][version] = "1.0-rc3"
projects[vt_default][patch][] = "http://drupal.org/files/issues/844930_move-tab-and-fix-package-in-info.patch"
projects[vt_default][patch][] = "http://drupal.org/files/issues/960758_unset-default-tab-when-empty.patch"

; FEATURES

projects[biocomp][type] = module
projects[biocomp][directory_name] = features_custom
projects[biocomp][download][type] = git
projects[biocomp][download][url] = git://github.com/patcon/biocomp.git

; LIBRARIES

; jQuery UI
libraries[jquery_ui][download][type] = "get"
libraries[jquery_ui][download][url] = "http://jquery-ui.googlecode.com/files/jquery.ui-1.6.zip"
libraries[jquery_ui][directory_name] = "jquery.ui"
