s file was auto-generated by drush_make
core = 6.x

projects[drupal][version] = "6.19"

; Modules
projects[admin_menu][version] = "1.6"

projects[content_profile][version] = "1.0"

projects[ctools][version] = "1.7"

projects[data][version] = "1.0-alpha14"

projects[date][subdir] = "date"
projects[date][version] = "2.6"

projects[diff][version] = "2.1"

projects[features][version] = "1.0"

projects[feeds][version] = "1.0-beta9"

projects[feeds_tamper][version] = "1.0-alpha3"

projects[filefield][version] = "3.7"

projects[install_profile_api][version] = "2.1"

projects[job_scheduler][version] = "1.0-beta3"

projects[location][version] = "3.1"

projects[schema][version] = "1.7"
